### PR TITLE
Make platforms a list of strings

### PR DESCRIPTION
**Pull request by imjasonh**
This is a breaking API change.

### CODE REVIEW

**Review by mattmoor — APPROVED** [review]
I wonder if @nsmith5 knows any magic to allow string or list of strings 🤔

**Comment by nsmith5** [comment]
@mattmoor Nah I don't know of anything. Terraform doesn't appear to support anything like an algebriac data type on their type system. They're pretty much 1:1 to the builtin go types (map, list, string, number etc). If you ask in the name of upgrade stability, I think the usual pattern is to just choose a new field name and deprecate the old field with e.g

```go
&schema.Schema{
  Deprecated: "Use platform_lists field instead",
}
```

**Comment by mattmoor** [comment]
Cool, thanks!

**Comment by imjasonh** [comment]
I'm not too worried about upgrade stability at this early point, I'd rather just rip the band-aid while we have ~1 user. But it's good to know that `Deprecated` is an option in the future!

**Pull request merged**
